//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Switching_Management_System_Client.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkPlan_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkPlan_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mini_Switching_Management_System_Client.Model.Resources.WorkPlan_Resources", typeof(WorkPlan_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date: .
        /// </summary>
        public static string Label_end_date {
            get {
                return ResourceManager.GetString("Label_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work plan ID: .
        /// </summary>
        public static string Label_id {
            get {
                return ResourceManager.GetString("Label_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work plan name: .
        /// </summary>
        public static string Label_name {
            get {
                return ResourceManager.GetString("Label_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator name: .
        /// </summary>
        public static string Label_operator_name {
            get {
                return ResourceManager.GetString("Label_operator_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator surname: .
        /// </summary>
        public static string Label_operator_surname {
            get {
                return ResourceManager.GetString("Label_operator_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date: .
        /// </summary>
        public static string Label_start_date {
            get {
                return ResourceManager.GetString("Label_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work plan status: .
        /// </summary>
        public static string Label_status {
            get {
                return ResourceManager.GetString("Label_status", resourceCulture);
            }
        }
    }
}
