//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkPlan", Namespace="")]
    public partial class WorkPlan : object
    {
        
        private string EndDateField;
        
        private int IDField;
        
        private System.Collections.ObjectModel.ObservableCollection<ServerReference.Instruction> InstructionsField;
        
        private string NameField;
        
        private string OperatorNameField;
        
        private string OperatorSurnameField;
        
        private string StartDateField;
        
        private ServerReference.WorkPlanStates StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ServerReference.Instruction> Instructions
        {
            get
            {
                return this.InstructionsField;
            }
            set
            {
                this.InstructionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorName
        {
            get
            {
                return this.OperatorNameField;
            }
            set
            {
                this.OperatorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorSurname
        {
            get
            {
                return this.OperatorSurnameField;
            }
            set
            {
                this.OperatorSurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServerReference.WorkPlanStates State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Instruction", Namespace="")]
    public partial class Instruction : object
    {
        
        private int NumberField;
        
        private System.Collections.ObjectModel.ObservableCollection<ServerReference.Switch> SwitchesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ServerReference.Switch> Switches
        {
            get
            {
                return this.SwitchesField;
            }
            set
            {
                this.SwitchesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkPlanStates", Namespace="")]
    public enum WorkPlanStates : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Executed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Switch", Namespace="")]
    public partial class Switch : object
    {
        
        private bool StateField;
        
        private int Switch_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Switch_ID
        {
            get
            {
                return this.Switch_IDField;
            }
            set
            {
                this.Switch_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Substation", Namespace="")]
    public partial class Substation : object
    {
        
        private System.Collections.ObjectModel.ObservableCollection<ServerReference.Feeder> FeedersField;
        
        private int IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ServerReference.Feeder> Feeders
        {
            get
            {
                return this.FeedersField;
            }
            set
            {
                this.FeedersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Feeder", Namespace="")]
    public partial class Feeder : object
    {
        
        private int IDField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<ServerReference.Switch> SwitchesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ServerReference.Switch> Switches
        {
            get
            {
                return this.SwitchesField;
            }
            set
            {
                this.SwitchesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerReference.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ServerReference.CompositeType GetDataUsingDataContract(ServerReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServerReference.CompositeType> GetDataUsingDataContractAsync(ServerReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWorkPlans", ReplyAction="http://tempuri.org/IService1/GetWorkPlansResponse")]
        System.Collections.ObjectModel.ObservableCollection<ServerReference.WorkPlan> GetWorkPlans();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWorkPlans", ReplyAction="http://tempuri.org/IService1/GetWorkPlansResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ServerReference.WorkPlan>> GetWorkPlansAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveWorkPlan", ReplyAction="http://tempuri.org/IService1/SaveWorkPlanResponse")]
        bool SaveWorkPlan(ServerReference.WorkPlan workPlans);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveWorkPlan", ReplyAction="http://tempuri.org/IService1/SaveWorkPlanResponse")]
        System.Threading.Tasks.Task<bool> SaveWorkPlanAsync(ServerReference.WorkPlan workPlans);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNewWorkPlanUniqueID", ReplyAction="http://tempuri.org/IService1/GetNewWorkPlanUniqueIDResponse")]
        int GetNewWorkPlanUniqueID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNewWorkPlanUniqueID", ReplyAction="http://tempuri.org/IService1/GetNewWorkPlanUniqueIDResponse")]
        System.Threading.Tasks.Task<int> GetNewWorkPlanUniqueIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubstations", ReplyAction="http://tempuri.org/IService1/GetSubstationsResponse")]
        System.Collections.ObjectModel.ObservableCollection<ServerReference.Substation> GetSubstations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubstations", ReplyAction="http://tempuri.org/IService1/GetSubstationsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ServerReference.Substation>> GetSubstationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveSubstation", ReplyAction="http://tempuri.org/IService1/SaveSubstationResponse")]
        bool SaveSubstation(ServerReference.Substation substation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveSubstation", ReplyAction="http://tempuri.org/IService1/SaveSubstationResponse")]
        System.Threading.Tasks.Task<bool> SaveSubstationAsync(ServerReference.Substation substation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditSubstation", ReplyAction="http://tempuri.org/IService1/EditSubstationResponse")]
        bool EditSubstation(ServerReference.Substation substation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditSubstation", ReplyAction="http://tempuri.org/IService1/EditSubstationResponse")]
        System.Threading.Tasks.Task<bool> EditSubstationAsync(ServerReference.Substation substation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNewSubstationUniqueID", ReplyAction="http://tempuri.org/IService1/GetNewSubstationUniqueIDResponse")]
        int GetNewSubstationUniqueID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNewSubstationUniqueID", ReplyAction="http://tempuri.org/IService1/GetNewSubstationUniqueIDResponse")]
        System.Threading.Tasks.Task<int> GetNewSubstationUniqueIDAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IService1Channel : ServerReference.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServerReference.IService1>, ServerReference.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public ServerReference.CompositeType GetDataUsingDataContract(ServerReference.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ServerReference.CompositeType> GetDataUsingDataContractAsync(ServerReference.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ServerReference.WorkPlan> GetWorkPlans()
        {
            return base.Channel.GetWorkPlans();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ServerReference.WorkPlan>> GetWorkPlansAsync()
        {
            return base.Channel.GetWorkPlansAsync();
        }
        
        public bool SaveWorkPlan(ServerReference.WorkPlan workPlans)
        {
            return base.Channel.SaveWorkPlan(workPlans);
        }
        
        public System.Threading.Tasks.Task<bool> SaveWorkPlanAsync(ServerReference.WorkPlan workPlans)
        {
            return base.Channel.SaveWorkPlanAsync(workPlans);
        }
        
        public int GetNewWorkPlanUniqueID()
        {
            return base.Channel.GetNewWorkPlanUniqueID();
        }
        
        public System.Threading.Tasks.Task<int> GetNewWorkPlanUniqueIDAsync()
        {
            return base.Channel.GetNewWorkPlanUniqueIDAsync();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ServerReference.Substation> GetSubstations()
        {
            return base.Channel.GetSubstations();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ServerReference.Substation>> GetSubstationsAsync()
        {
            return base.Channel.GetSubstationsAsync();
        }
        
        public bool SaveSubstation(ServerReference.Substation substation)
        {
            return base.Channel.SaveSubstation(substation);
        }
        
        public System.Threading.Tasks.Task<bool> SaveSubstationAsync(ServerReference.Substation substation)
        {
            return base.Channel.SaveSubstationAsync(substation);
        }
        
        public bool EditSubstation(ServerReference.Substation substation)
        {
            return base.Channel.EditSubstation(substation);
        }
        
        public System.Threading.Tasks.Task<bool> EditSubstationAsync(ServerReference.Substation substation)
        {
            return base.Channel.EditSubstationAsync(substation);
        }
        
        public int GetNewSubstationUniqueID()
        {
            return base.Channel.GetNewSubstationUniqueID();
        }
        
        public System.Threading.Tasks.Task<int> GetNewSubstationUniqueIDAsync()
        {
            return base.Channel.GetNewSubstationUniqueIDAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54862/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
